### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by MarkCatchpole** [ARMmbed/connected-lights#10]
Hi!
I am using connected-lights to help me get my head round ARM's IOT offering. I am an experienced electronics engineer with very limited s/w experience and I'm new to Github(hacker alert!). I have been following the instructions with a K64 board although for now (being lazy!) I plan to just use the K64's on board LED and a push button for the electronics part.  
I have so far got up to the adding connectivity section with a simple working program generated using the mbed online IDE. I then add in the libraries for the simple-mbed-client and easy-connect (not selecting the update sub-libraries box) and put in the initial skeleton code that sets up a connection. 
Compile gives the following error:

Error: Cannot open source input file "platform/mbed_wait_api.h": No such file or directory in "easy-connect/atmel-rf-driver/source/at24mac.h", Line: 22, Col: 37

Do I need to use an earlier version of the simple-mbed-client and easy-connect libraries?

All suggestions gratefully received.

Mark

**Comment by janjongboom** [comment]
Hi @MarkCatchpole, indeed annoying, will update the docs shortly. Quick way to fix it is to pin easy-connect to revision cb933fb19cda (through the revisions panel).

**Comment by MarkCatchpole** [comment]
Hi @janjongboom ,
Thanks for your support.
Your fix has sorted out the error for me. However there is now a new one associated with the simple-mbed-client:

Error: Cannot open source input file "source/include/sn_coap_protocol_internal.h": No such file or directory in "simple-mbed-client/mbed-client/mbed-client-c/source/sn_grs.c", Line: 31, Col: 55

Regards

    Mark

**Comment by MarkCatchpole** [comment]
I switched the simple-mbed-client to 16:cb980bd which compiled and runs ok: connects over ethernet and registers device. Onwards and upwards to the cloud!

**Comment by janjongboom** [comment]
Thanks for reporting. I'll pin the versions of easy-connect and simple-mbed-client for the future, that should prevent these kind of shenanigans.

**Comment by janjongboom** [comment]
Fixed in fae088fdfca6a72d4048a0dd2d80cad24f231d9a
